### ISSUE TITLE
Ubuntu image won't boot

### ISSUE THREAD

**Issue by Xe** [initdc/rootfs-tools#2]
I tried booting my VisionFive2 on the Ubuntu image you released and it's not booting. It's not showing up on my network and the HDMI port has no output. How should I debug this further? I'm using a dual ethernet model and putting my ethernet cable on the right-most option. Should I use the ethernet cable closest to the HDMI port? Should I acquire a USB->Serial device to get the output that way?

**Comment by initdc** [comment]
Try this guide, make sure you can see Eth devices

https://ubuntu.com/server/docs/network-configuration

**Comment by initdc** [comment]
Try this guide, make sure you can see Eth devices

https://ubuntu.com/server/docs/network-configuration
