### ISSUE TITLE
Are ROS2 packages preinstalled? 

### ISSUE THREAD

**Issue by kulkarni-raunak** [initdc/rootfs-tools#4]
I found out about this repository from [this](https://www.reddit.com/r/RISCV/comments/10kgl6e/ros2_humble_ubuntu_2204_on_the_starfive/).

I'm just wondering if it has preinstalled ROS2-humble packages based on RISC-V architecture.

**Comment by initdc** [comment]
I never used ROS before, I am not sure the package I searched is the correct one.
https://packages.ubuntu.com/search?keywords=ros&searchon=names&suite=jammy&section=all

If package manager provide the `ros`, you can simple `chroot` the image and install it (make sure disk space is OK).
If package manager not provide the `ros`, you have to do some dirty work. 
You may need build the package by your self, install the binary when you get done.
like this: https://github.com/initdc/rootfs-tools/blob/master/vendor-resources/intel-edison/root/config.sh#L18
